name: deadlock tests

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch: {}

jobs:

  julia:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        julia-version: ["1.12", "lts"]
        shell: [bash, pwsh]
      fail-fast: false
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - name: Check out github
        uses: actions/checkout@v5

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}

      - name: download large repo
        run: git clone --recursive https://github.com/stan-dev/cmdstan.git --depth 1 --shallow-submodules

      - name: run make inside julia
        timeout-minutes: 60
        run: |
          julia --project=. ./run.jl
