name: bridgestan tests

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch: {}

env:
  CACHE_VERSION: 3

# only run one copy per PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  julia:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest]
        julia-version: ["1"]
        shell: [bash, pwsh]
      fail-fast: false
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - name: Check out github
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}

      - name: download large repo
        run: git clone --recursive https://github.com/stan-dev/cmdstan.git --depth 1 --shallow-submodules

      - name: run make inside julia
        run: |
          cd cmdstan
          julia --project=. --eval "run(`make build`)"
